fruit = input("Enter your favorite fruit:")
drink = input("Enter your favorite drink:")
snack = input("Enter your favorite drink:")
vegetable = input("Enter your favorite vegetable: ")
print("list:")
print(f"1. {fruit}")
print(f"2. {drink}")
print(f"3. {snack}")
print(f"4. {vegetable}")